=== Unford/JWD_xml/src/main/resources/input/deposits.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.feshenko.com/banks"
  xmlns:tns="http://www.feshenko.com/banks"
  elementFormDefault="qualified">

  <element name="abstract-deposit" type="tns:AbstractDeposit" abstract="true"/>

  <element name="cash-deposit" type="tns:CashDeposit" substitutionGroup="tns:abstract-deposit" abstract="true"/>

  <element name="metal-deposit" type="tns:MetalDeposit" substitutionGroup="tns:abstract-deposit"/>

  <element name="term-deposit" type="tns:TermDeposit" substitutionGroup="tns:cash-deposit"/>

  <element name="banks">
    <complexType>
      <sequence>
        <element ref="tns:abstract-deposit"
                 maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>

  <complexType name="AbstractDeposit">
    <sequence>
      <element name="country" type="tns:Country"/>
      <element name="depositor" type="string"/>
    </sequence>
    <attribute name="bank-name" type="string" use="optional"/>
    <attribute name="account-id" type="tns:DepositId" use="required"/>
  </complexType>

  <complexType name="CashDeposit">
    <complexContent>
      <extension base="tns:AbstractDeposit">
        <sequence>
          <element name="currency" type="tns:Currency"/>
          <element name="amount-on-deposit" type="tns:PositiveDouble"/>
          <element name="profitability" type="tns:Percent"/>
          <element name="capitalization" type="boolean" default="false"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="MetalDeposit">
    <complexContent>
      <extension base="tns:AbstractDeposit">
        <sequence>
          <element name="mass" type="tns:PositiveDouble"/>
          <element name="metal" type="tns:Metal"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>

  <complexType name="TermDeposit">
    <complexContent>
      <extension base="tns:CashDeposit">
        <sequence>
          <element name="time-constraints" type="date"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>


  <simpleType name="Metal">
    <restriction base="string">
      <enumeration value="gold"/>
      <enumeration value="silver"/>
      <enumeration value="platinum"/>
      <enumeration value="palladium"/>
    </restriction>
  </simpleType>

  <simpleType name="Currency">
    <restriction base="string">
      <enumeration value="USD"/>
      <enumeration value="EUR"/>
      <enumeration value="GBP"/>
      <enumeration value="BYN"/>
      <enumeration value="RUB"/>
      <enumeration value="CAD"/>
      <enumeration value="UAH"/>
    </restriction>
  </simpleType>

  <simpleType name="Country">
    <restriction base="string">
      <enumeration value="usa"/>
      <enumeration value="uk"/>
      <enumeration value="belarus"/>
      <enumeration value="russia"/>
      <enumeration value="canada"/>
      <enumeration value="ukraine"/>
    </restriction>
  </simpleType>

  <simpleType name="DepositId">
    <restriction base="ID">
      <pattern value="[A-Z]{2}\d{2}[A-Z]{4}\d{12}"/>
    </restriction>
  </simpleType>

  <simpleType name="PositiveDouble">
    <restriction base="double">
      <minExclusive value="0"/>
      <maxInclusive value="999999"/>
    </restriction>
  </simpleType>

  <simpleType name="Percent">
    <restriction base="double">
      <minExclusive value="0"/>
      <maxInclusive value="1"/>
    </restriction>
  </simpleType>

</schema>

=== Unford/JWD_xml/src/test/resources/input/shortDeposits.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.feshenko.com/banks"
       xsi:schemaLocation="http://www.feshenko.com/banks deposits.xsd">

    <metal-deposit account-id="BY23GDSE313123461543" bank-name="Техно-банк">
        <country>belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <mass>1.4</mass>
        <metal>gold</metal>
    </metal-deposit>

    <term-deposit bank-name="Альфа-банк" account-id="BY13MSJO134137053543">
        <country>russia</country>
        <depositor>Маковский Петр Николаевич</depositor>
        <currency>RUB</currency>
        <amount-on-deposit>1132.5</amount-on-deposit>
        <profitability>0.40</profitability>
        <capitalization>false</capitalization>
        <time-constraints>2022-12-01</time-constraints>
    </term-deposit>

    <metal-deposit  account-id="US63BGSJ064137153443">
        <country>usa</country>
        <depositor>Гумилев Николай Степанович</depositor>
        <mass>14.2</mass>
        <metal>palladium</metal>
    </metal-deposit>

    
</banks>

=== Unford/JWD_xml/src/main/resources/input/deposits.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.feshenko.com/banks"
       xsi:schemaLocation="http://www.feshenko.com/banks deposits.xsd">

    <metal-deposit bank-name="Альфа-банк" account-id="AB23ewrs313153218543">
        <country>Belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <amount-on-deposit>333.5</amount-on-deposit>
        <profitability>0.7</profitability>
        <capitalization>true</capitalization>
        <metal>gold</metal>
    </metal-deposit>
    <term-deposit bank-name="Альфа-банк" account-id="AB23ewrs313153218533">
        <country>Belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <amount-on-deposit>333.5</amount-on-deposit>
        <profitability>1.0</profitability>
        <capitalization>true</capitalization>
        <time-constraints>2021-12-23</time-constraints>
    </term-deposit>
    <metal-deposit bank-name="Альфа-банк" account-id="AB23ewrs313153211543">
        <country>Belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <amount-on-deposit>333.5</amount-on-deposit>
        <profitability>1.0</profitability>
        <capitalization>true</capitalization>
        <metal>gold</metal>
    </metal-deposit>
    <term-deposit bank-name="Альфа-банк" account-id="AB23ewrs313154218543">
        <country>Belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <amount-on-deposit>333.5</amount-on-deposit>
        <profitability>0.8</profitability>
        <capitalization>true</capitalization>
        <time-constraints>2021-12-23</time-constraints>
    </term-deposit>
</banks>

=== Unford/JWD_xml/src/test/resources/input/depositsInvalid.xml
<?xml version="1.0" encoding="UTF-8"?>
<banks xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
       xmlns="http://www.feshenko.com/banks"
       xsi:schemaLocation="http://www.feshenko.com/banks deposits.xsd">

    <metal-deposit account-id="BY234GDSE313123461543" bank-name="Техно-банк">
        <country>belarus</country>
        <depositor>Фещенко Владимир Дмитриевич</depositor>
        <mass>1.4</mass>
        <metal>gold</metal>
    </metal-deposit>

    <term-deposit bank-name="Альфа-банк" account-id="BY13MSJO134137053543">
        <country>russia</country>
        <depositor>Маковский Петр Николаевич</depositor>
        <currency>RUB</currency>
        <amount-on-deposit>1132.5</amount-on-deposit>
        <profitability>0.40</profitability>
        <capitalization>false</capitalization>
        <time-constraints>2022-12-01</time-constraints>
    </term-deposit>

    <metal-deposit bank-name="ВТБ" account-id="US643BGSJ064137153443">
        <country>usa</country>
        <depositor>Гумилев Николай Степанович</depositor>
        <mass>14.2</mass>
        <metal>palladium</metal>
    </metal-deposit>

    <term-deposit account-id="UK63ZXCX064537153113">
        <country>ukraine</country>
        <depositor>Ахматова Анна Андреевна</depositor>
        <currency>CAD</currency>
        <amount-on-deposit>3513.5</amount-on-deposit>
        <orice>0.15</profitability>
        <capitalization>true</capitalization>
        <time-constraints>2022-05-05</time-constraints>
    </term-deposit>

    <metal-deposit account-id="AU64GDSE631123631343">
        <country>russia</country>
        <depositor>Блок Александр Александрович</depositor>
        <mass>15.4</mass>
        <metal>silver</metal>
    </metal-deposit>

    <term-deposit bank-name="Беларусь-банк" account-id="BY83MBBO136272053543">
        <country>uk</country>
        <depositor>Брюсов Валерий Яковлевич</depositor>
        <currency>RUB</currency>
        <amount-on-deposit>2532</amount-on-deposit>
        <profitability>0.20</profitability>
        <capitalization>true</capitalization>
        <time-constraints>2025-07-15</time-constraints>
    </term-deposit>

    <metal-deposit account-id="BY61BGVJ064137933400" bank-name="Техно-банк">
        <country>belarus</country>
        <depositor>Бальмонт Константин Дмитриевич</depositor>
        <mass>39.2</mass>
        <metal>platinum</metal>
    </metal-deposit>

    <term-deposit  account-id="UJ65NERO561337833141" bank-name="Супер-банк">
        <country>canada</country>
        <depositor>Мандельштам Осип Эмильевич</depositor>
        <currency>GBP</currency>
        <amount-on-deposit>513.76</amount-on-deposit>
        <profitability>0.2</profitability>
        <capitalization>false</capitalization>
        <time-constraints>2030-12-15</time-constraints>
    </term-deposit>

    <metal-deposit account-id="DR03MOSE631123634343">
        <country>uk</country>
        <depositor>Бунин Иван Алексеевич</depositor>
        <mass>300</mass>
        <metal>silver</metal>
    </metal-deposit>

    <term-deposit bank-name="ВТБ" account-id="RU15YBER104271586343">
        <country>ukraine</country>
        <depositor>Введенский Александр Иванович</depositor>
        <currency>UAH</currency>
        <amount-on-deposit>753.2</amount-on-deposit>
        <profitability>0.30</profitability>
        <capitalization>false</capitalization>
        <time-constraints>2022-06-12</time-constraints>
    </term-deposit>

    <metal-deposit bank-name="Альфа-банк" account-id="RU12BHYJ066932933402">
        <country>russia</country>
        <depositor>Волошин Максимилиан Александрович</depositor>
        <mass>14.2</mass>
        <metal>gold</metal>
    </metal-deposit>

    <term-deposit bank-name="БелВЭБ" account-id="BY31HTOE561330093421">
        <country>belarus</country>
        <depositor>Есенин Сергей Александрович</depositor>
        <currency>BYN</currency>
        <amount-on-deposit>1290.4</amount-on-deposit>
        <profitability>0.4</profitability>
        <capitalization>false</capitalization>
        <time-constraints>2022-03-16</time-constraints>
    </term-deposit>
</banks>
